site_name: CrystalExpressSDK-Doc
pages:
- Home Page: 'index.md'
- 'Change Log': 'changelog.md'
- 'Before Integration': 'before.md'
- 'Initialize':
    - 'AndroidManifest.xml': 'androidmanifest.md'
    - 'Activity': 'activity_setting.md'
- 'AD integration':
    - 'Open Splash': 'opensplash.md'
    - 'Interstitial Splash': 'interstitial.md'
    - 'In-Stream': 'stream.md'
    - 'In-Read': 'content.md'
- 'Proguard': 'proguard.md'
- 'Preview Mode': 'preview.md'
- 'Ad Event Callback': 'adevent.md'
- 'Checkpoint': 'checkpoint.md'
- 'Trouble Shooting': 'faq.md'
- 'API': 'api.md'
- 'Appendix': 'naming.md'
theme: readthedocs
